### ISSUE TITLE
Exception error 

### ISSUE THREAD

**Issue by armanth14** [NeutrinosPlatform/cordova-plugin-mobile-ocr#10]
Good afternoon,

after taking the photo, the function "textocr" returns a string that says exception only, and validates the cordova and anddrroid versions and according to the requirements everything is in order.
I attach my project, thank you very much
[nbproject.zip](https://github.com/NeutrinosPlatform/cordova-plugin-mobile-ocr/files/2985796/nbproject.zip)

**Comment by ChrisTomAlx** [comment]
It would seem you are using the plugin as below :
`textocr.recText(0, 3, image, onSuccess, onFail);`

From plugin version 2.0.0 and above you need to use it as below : 
`textocr.recText(0, image, onSuccess, onFail);`
> Notice that I removed the "3" which was the returnType

Let  me know if this helps :) 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by armanth14** [comment]
Hello

Yes, now it works better, but, the recognizedText variable is returned as an object, do you know what the property is that the text shows?

Thanks

**Comment by ChrisTomAlx** [comment]
Yea will be adding details about the object to the readme shortly. 
In the meantime you could view the exact object along with example objects in the readme here : https://github.com/NeutrinosPlatform/cordova-plugin-ml-text

Scroll to the very bottom of the readme to view it

> Just in case you did not already know :) You can console.log the object to see the entire object

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by armanth14** [comment]
Thank you very much, you are the best !! : D

**Comment by ChrisTomAlx** [comment]
My Pleasure!!

Have a nice day!
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
