### ISSUE TITLE
barcodes detector

### ISSUE THREAD

**Issue by eboily** [NeutrinosPlatform/cordova-plugin-mobile-ocr#12]
Are there any current effort or plans to implement the interface to the barcodes detector?

**Comment by ChrisTomAlx** [comment]
Hey @eboily 
You can use this [plugin](https://github.com/phonegap/phonegap-plugin-barcodescanner) for barcode scanning. 
I would prefer not to make this plugin too bulky by implementing functionality that already exists.
Sorry I could not be of more help.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
