### ISSUE TITLE
ocr fail

### ISSUE THREAD

**Issue by sdegunst** [NeutrinosPlatform/cordova-plugin-mobile-ocr#13]
After use of cordova-plugin-document-scanner, I try to launch cordova-plugin-mobile-ocr (recText with returnType 2) and I only get the word "Exception".
It seems to be a result of an error catched in line 100 in Textocr.java...

when I launch adb locat, I have the following crash log

04-05 19:13:17.707 28191 28191 D CordovaActivity: Incoming Result. Request code = 99
04-05 19:13:17.707 28191 28191 D CordovaInterfaceImpl: Sending activity result to plugin
04-05 19:13:17.712 28191 28191 D CordovaActivity: Started the activity.
04-05 19:13:17.712 28191 28191 D CordovaActivity: Resumed the activity.
04-05 19:13:17.714 28191  1199 W System.err: java.lang.StringIndexOutOfBoundsException: length=1; regionStart=0; regionLength=6
04-05 19:13:17.715 28191  1199 W System.err:    at java.lang.String.startEndAndLength(String.java:298)
04-05 19:13:17.715 28191  1199 W System.err:    at java.lang.String.substring(String.java:1087)
04-05 19:13:17.715 28191  1199 W System.err:    at com.neutrinos.ocrplugin.Textocr$1.run(Textocr.java:72)
04-05 19:13:17.715 28191  1199 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-05 19:13:17.715 28191  1199 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-05 19:13:17.715 28191  1199 W System.err:    at java.lang.Thread.run(Thread.java:818)
04-05 19:13:17.715 28191  1199 W CordovaPlugin: Attempted to send a second callback for ID: Textocr533608263
04-05 19:13:17.715 28191  1199 W CordovaPlugin: Result was: "Error"
04-05 19:13:17.725 28191  1199 W DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.

**Comment by sdegunst** [comment]
I use the following version
cordova-plugin-mobile-ocr : 2.0.0
cordova-plugin-document-scanner : 3.0.0

**Comment by ChrisTomAlx** [comment]
So returnType is no longer accepted from plugin version 2.x.x
So the recText call should look like this. 
returnType is no longer required because all of them are returned as an object.
`textocr.recText(sourceType, uriOrBase, successCallback, errorCallback)`

### Usage Example
```js
scan.scanDoc(1, onSuccess, onFail);

function onSuccess(imageURI) {
      textocr.recText(0, /*3,*/ imageURI, onSuccess, onFail); // removed returnType (here 3) from version 2.0.0
      // for sourceType Use 0,2 // 1,3,4 won't work
      function onSuccess(recognizedText) {
            //var element = document.getElementById('pp');
            //element.innerHTML=recognizedText;
            //Use above two lines to show recognizedText in html
            console.log(recognizedText);
            alert(recognizedText);
      }
      function onFail(message) {
            alert('Failed because: ' + message);
      }
}
function onFail(message) {
      alert('Failed because: ' + message);
}

```
Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by sdegunst** [comment]
ok, I didn't notice... (and the description is not up to date on npmjs)
I try this and give you a feed back.

**Comment by sdegunst** [comment]
OK, I get an object... could you give us some information about this object  ?

**Comment by ChrisTomAlx** [comment]
Here you go. Added this and example objects as the last section in the github readme. The basic structure of the object is as follows :- 

 - **blocks**
   - **blocktext** - **Array** that contains each text block
   - **blocklanguages** - **Array** of languages (Currently returns unusable values)
   - **blockconfidence** - **Array** of confidence values (Currently return nil for on-Device text recognition) 
   - **blockpoints** - **Array** of objects of four points each that represent a block drawn around the text
     - x1 - Key (Example to get x1 of the first text block :- recognizedText.blocks.blockpoints[0].x1)
     - y1 - Key
     - x2 - Key
     - y2 - Key
     - x3 - Key
     - y3 - Key
     - x4 - Key
     - y4 - Key
   - **blockframe** - **Array** of objects that contain origin point and size of the rectangle that holds text
     - x - Key (Example to get x from blockframe of the first text block :- recognizedText.blocks.blockframe[0].x)
     - y - Key
     - height - Key
     - width - Key
 - **lines**
   - **linetext** - **Array** that contains each text block
   - **linelanguages** - **Array** of languages (Currently returns unusable values)
   - **lineconfidence** - **Array** of confidence values (Currently return nil for on-Device text recognition) 
   - **linepoints** - **Array** of objects of four points each that represent a block drawn around the text
        - x1 - Key
        - y1 - Key
        - x2 - Key
        - y2 - Key
        - x3 - Key
        - y3 - Key
        - x4 - Key
        - y4 - Key
   - **lineframe** - **Array** of objects that contain origin point and size of the rectangle that holds text
     - x - Key
     - y - Key
     - height - Key
     - width - Key
 - **words**
   - **wordtext** - **Array** that contains each text block
   - **wordlanguages** - **Array** of languages (Currently returns unusable values)
   - **wordconfidence** - **Array** of confidence values (Currently return nil for on-Device text recognition) 
   - **wordpoints** - **Array** of objects of four points each that represent a block drawn around the text
        - x1 - Key
        - y1 - Key
        - x2 - Key
        - y2 - Key
        - x3 - Key
        - y3 - Key
        - x4 - Key
        - y4 - Key
   - **wordframe** - **Array** of objects that contain origin point and size of the rectangle that holds text
     - x - Key
     - y - Key
     - height - Key
     - width - Key

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Okay so I updated the npm readme as well (Plugin version 2.0.1). Closing this issue for now. Please reopen if you have questions related to this issue or create  a new issue if you have a new question.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
