### ISSUE TITLE
ionic 4 app.module.ts import MobileOCR not working Solution found

### ISSUE THREAD

**Issue by badalpatel6534** [NeutrinosPlatform/cordova-plugin-mobile-ocr#16]
Hello Community,

**Issue**:

Recently I used mobile ocr plugin in ionic 4 
There is mistake in documentation:
import { MobileOCR } from '@ionic-native/ocr/ngx';
This MobileOCR should not be imported 

**Solution**:

change 
From: import { MobileOCR } from '@ionic-native/ocr/ngx';
To: import { OCR } from '@ionic-native/ocr/ngx';
This will work perfectly

hope so documentation will update and dev will use from MobileOCR to OCR
 

![image](https://user-images.githubusercontent.com/30089947/63586738-bb1a5000-c5bf-11e9-8529-5c454344c65d.png)

**Comment by ChrisTomAlx** [comment]
Hey @badalpatel6534 
Thanks a lot for bringing this to the community's attention. I will pin this issue to the top and close it.

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
