### ISSUE TITLE
Application Stopped!

### ISSUE THREAD

**Issue by Serkan-Karacelikler** [NeutrinosPlatform/cordova-plugin-mobile-ocr#19]
I get an application stopped error when I enter the background after installing the add-in

**Comment by ChrisTomAlx** [comment]
Hey @Serkan-Karacelikler 
Could you give more info on the problem. Also could you share a sample project in which you are able to reproduce the issue

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by Serkan-Karacelikler** [comment]
@ChrisTomAlx 
I pass the application to the background after scanning a document, the application gives a stopped error

**Comment by ChrisTomAlx** [comment]
Please share a sample project so I can reproduce it on my end. Also a video of the issue would be great so I understand exactly when you are seeing this issue.

Please also answer the following questions :-
- Which platform are you seeing this issue on? iOS or Android or both? 
- Which cordova version are you using?
- Which other plugins are present in your project?

Cheers
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by Serkan-Karacelikler** [comment]
Thank you for your interest. I noticed that the problem is relevant to the camera plugin.

**Comment by ChrisTomAlx** [comment]
No worries :) 
Glad you were able to figure it out.

Cheers
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
