### ISSUE TITLE
[Correction] Missing Podfile entry

### ISSUE THREAD

**Issue by vshy108** [NeutrinosPlatform/cordova-plugin-mobile-ocr#2]
I need to add 

`pod 'GoogleMobileVision/TextDetector'`

to PodFile so that it will download the necessary SDK file for ios build.

May be it should be included in the README.md file explanation? thanks

**Comment by ChrisTomAlx** [comment]
Hey @vshy108 

The 'GoogleMobileVision/TextDetector' pod dependency is bundled along with the plugin in the plugin.xml. After install of the plugin you need to follow the following steps in iOS as mentioned in the readme.

- Once the iOS platform is added in command line, change directory to where podfile is found. Example location :- (myapp/platforms/ios).
- Make sure you have cocoapods installed then in command line do `pod update`.
- Now open myapp.xcworkspace which is usually found in the same directory as the podfile, then build and run.
>Note :- if you use myapp.xcodeproj to build and run, it will not work and it will show a linker error.

You followed the above steps and it did not work? Did you still have to add `pod 'GoogleMobileVision/TextDetector'` manually?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by vshy108** [comment]
After I installed the plugin with Visual studio 2017 by opening designer view of config.xml of my project, PodFile is not created under ios folder. Hence I manually created new PodFile and fill in the dependency in my case.

The following line in plugin.xml will create the new PodFile if not found any?
`<framework src="GoogleMobileVision/TextDetector" type="podspec" spec="~> 1.3.2"/> `

**Comment by ChrisTomAlx** [comment]
Oh cool. If you are manually creating the podfile then you will have to add it. If you use cordova, then cordova will automatically add the podfile and all you have to do is pod update. 

Anyhow thank you for raising this issue :)
I will reference this issue in the readme for other people who manually create their podfile.

Cheers and Have a nice day!,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
