### ISSUE TITLE
Arabic Support

### ISSUE THREAD

**Issue by MohamedFekry007** [NeutrinosPlatform/cordova-plugin-mobile-ocr#20]
Please why there is no arabic support ??

**Comment by ChrisTomAlx** [comment]
Hey @MohamedFekry007 
Unfortunately googles mobile vision library only supports latin based language for now.
You could however look at tesseract. They have a wide variety of languages. Although not as accurate as googles mobile vision, under the correct lighting it should get the job done.

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
