### ISSUE TITLE
Which languages does this library support ?

### ISSUE THREAD

**Issue by jalle007** [NeutrinosPlatform/cordova-plugin-mobile-ocr#21]
You haven't provided MOST important information here:
Which languages does this library support ?

**Comment by ChrisTomAlx** [comment]
Please consider reading the `readme` carefully before raising issues. This information has been provided there as a link.

Cheers
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
