### ISSUE TITLE
Text-recognizer not working

### ISSUE THREAD

**Issue by DarthegX** [NeutrinosPlatform/cordova-plugin-mobile-ocr#23]
Hi, I'm using cordova-plugin-mobile-ocr in my project and I try to use the plugin but after I pick a photo with the camera (on Android) the text recognizer function do not return anything.
When I pulse the buttom to recognize the app return this message in the console:

"Native: tried calling OCR.recText, but the OCR plugin is not installed. "
"Install the OCR plugin: 'ionic cordova plugin add cordova-plugin-mobile-ocr'"

But I have installed all the necessary dependencies previously.

**Comment by ChrisTomAlx** [comment]
Try debugging in chrome and see if `textocr.recText` is present there. If not, it means the plugin has not been installed

Cheers and have a nice day :)
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
