### ISSUE TITLE
ReferenceError: textocr is not defined

### ISSUE THREAD

**Issue by AlokGupta007** [NeutrinosPlatform/cordova-plugin-mobile-ocr#29]
Hi,

I am trying to test this plugin in phonegap android application. But getting this error.
Please give solution. Thanks in advance.
Here is the error : 
Error in Success callbackId: Camera1720476463 : ReferenceError: textocr is not defined
Cordova version - 9.0.0 (cordova-lib@9.0.1)
npm - 6.9.0
node -v  - v10.16.3

**Comment by ChrisTomAlx** [comment]
Hey @AlokGupta007 

This usually happens when you don't have the plugin installed properly.
Try `cordova plugins` from cli. Post the list you get here. You should have this plugin in that list.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by AlokGupta007** [comment]
I am using "cordova plugin add cordova-plugin-mobile-ocr" cli for installing api. In config.xml plugin configuration is not available after plugin installation. Please suggest the correct thing.

Thanks

**Comment by ChrisTomAlx** [comment]
Did you try as I suggested??
> Try `cordova plugins` from cli. Post the list you get here. You should have this plugin in that list.

Send a sample project over and I will test it out on my end.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
