### ISSUE TITLE
Does this plugin send info to Google servers?

### ISSUE THREAD

**Issue by rjurado01** [NeutrinosPlatform/cordova-plugin-mobile-ocr#31]
I want to use this plugin into client app but he is worried about the confidentiality of information.

Does this plugin send any kind of information to Google servers when internet is on?
Some tools like this send info to improve text recognition.

Thanks for your work.

**Comment by ChrisTomAlx** [comment]
Hey @rjurado01 

Sorry about the delayed response. As far as I know it does not. Only on first install it requires internet to download the recognition machine learned model. But if you do come across any network calls after the initial download please feel free to share I can look into it. Closing this issue for now. Drop a comment and I can reopen it.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
