### ISSUE TITLE
Error in Success callbackId: Camera709080135 : ReferenceError: textocr is not defined

### ISSUE THREAD

**Issue by nisanc** [NeutrinosPlatform/cordova-plugin-mobile-ocr#33]
I can build and data is returned using the latest version but when trying to use cordova phonegap build with version 1.0.1 so I can return LINES of text I receive the following error:
"Error in Success callbackId: Camera709080135 : ReferenceError: textocr is not defined"

XML file:
`		<plugin name="cordova-plugin-mobile-ocr"  source="npm" spec="1.0.1"/>`

html sample code:
  `   
	  
         function capturePhoto() {
		navigator.camera.getPicture(onSuccess, onFail, { quality: 100, correctOrientation: true });
 
		function onSuccess(imageData) {
			textocr.recText(0, 1, imageData, onSuccess, onFailx);
		}
		function onSuccess(recognizedText) {
	  		var recognizedText2 = JSON.stringify(recognizedText); 
            var element = document.getElementById('pp');
            element.innerHTML=recognizedText2;
            console.log(recognizedText2);
		}
		function onFail(message) {
            alert('Failed because: ' + message);
		}
	}
	function onFail(message) {
		alert('Failed because: ' + message);
	}

`

Javascript file:

        `	
	/*global cordova, module*/

	module.exports = {
		recText: function (sourceType, returnType, imageSource, successCallback, errorCallback) {
        cordova.exec(successCallback, errorCallback, "Textocr", "recText", [sourceType, returnType, imageSource]);

	    //recText: function (sourceType, imageSource, successCallback, errorCallback) {
	    //    cordova.exec(successCallback, errorCallback, "Textocr", "recText", [sourceType, imageSource]);
	    }
	};
	`

**Comment by ghost** [comment]
it looks like the plugin has not been installed.
try `phonegap plugins` or `cordova plugins` to check if the plugins are installedto check if the plugins are installed.
or try installing the plugin again from the terminal

**Comment by nisanc** [comment]
I am using the phonegap build service. It is installed from the XML file:
plugin name="cordova-plugin-mobile-ocr" source="npm" spec="1.0.1"

does version 1.0.1 exist on NPM?

**Comment by ghost** [comment]
maybe it's something with the network, I don't know. I'm also getting an error when trying to install version 3.1.1

**Comment by nisanc** [comment]
via the build log:
Plugin doesn't support this project's cordova-android version. **_cordova-android: 6.3.0, failed version requirement: >=6.4.0_**
Skipping 'cordova-plugin-mobile-ocr' for android

Is that saying I need cordova 6.3.0 ?

I am using version 7
>> name='phonegap-version' value='cli-7.1.0'

**Comment by ghost** [comment]
everything indicates that yes, 
maybe that can help you too [issue#14](https://github.com/NeutrinosPlatform/cordova-plugin-mobile-ocr/issues/14#issuecomment-487257297_)

**Comment by nisanc** [comment]
Thank you. I had to update the PG Build version to 8.0.0
preference name='phonegap-version' value='cli-8.0.0'

ironic it had to be increased to install and older version.
