### ISSUE TITLE
foundText: false issue with base64 image

### ISSUE THREAD

**Issue by dzungcao** [NeutrinosPlatform/cordova-plugin-mobile-ocr#35]
I am facing this issue with below base64 image. Hope someone can help to look into this. 

Thank you very much

Input:
--------------------------------
iVBORw0KGgoAAAANSUhEUgAAAGcAAABnCAYAAAAdQVz5AAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAZ6ADAAQAAAABAAAAZwAAAAA7gf8VAAAIXElEQVR4Ae2dbWwURRjHn9ltD8qbgEUx+MJrIggoWGivkIgviaKUNL1eAhERNEqI4hdU/CCmEdRgFImhkaBRBBQCLRRRUT4AEui1UFACKIFg8IMxKApYpIX2bnym9dre9Zm9q925u/aeSa63+8zsPDO//+7O7NzsFIADE2ACTIAJMAEmwASYABNgAkyACTABJsAEmAATYAJMgAkwASbABEB0OwYn/R64eC0bMjKzQVjZEAoOAiGyAcRAkCE7/vpadWCJ/TAZDoHYGoz/OPdSZriXVZJyqvQPAVvmg4R8LEE+1IYmojDN9ZIh1CR8/sk22/GUFdNL/FSLrzDvAjyNcSexIVzyxHrtrLeagl7Q6JmD4BciwHs6m13M46V4FLxlu2KmczlB17pyKv1ZYIcWQhBeQQ6Dms5sl4GQ2Uk5Ce0sDglHGQPF00GESvHmMkybxlSEEIdNZe2Ub+pfOXsL+0NPexUI+aRTRczFYZuTV/aNufz1Oae2OAFfLjbEm7H4Q/VVIGMuofU8fn5v+kj8FvICXnXYQ4g3tO2tJb4zoEqZuuJU+p5CYT7AMnriwHkau2J7sXt1AGTwAHgrzsVxTMonSb3emkRJqotfR9CvxqQnYD+meRNyy7+NmbYLJkgtcdQD5BX5IfbC5jqzlOfwAXMR5JZ96Zyua8d24InZcEVrCrKh3lKwZzp4UtfVGqizi2Bq2QmHdN0iKjXanMO+4dAgdyP4EVqqAi6BFPPwatmhTdPNIpJ/W6vyjUKm2JjDEC1bAT/jg+djkF9+SpumG0Yk97ZWVXQrDsF8h1xvc2Bbgx22B8G75ReHNN0yykpardT4mBRf4BPE7Q5lqICsXtMgb5N6Zkm7kDxxGj1rsI2ZoCUuYQXkjvPB3Rv+0abp5hHJaXMCvmdQmLVatgIW47PLSm18mkQkXpxK/0j8/eUHfJbpTTMWr+FY1jI6Lr2sie9K26E12M5ohIGNLEzrCZjYNqfK50NhHmx1H7F1DP64viDCkuY7iRNHllgozHIN7zocgp0FBTuvauLT0py429rhE4XYCbiTpCxlCeRsS6sHTJJDlDGBVw68EOU7vHsGMrPfC+/wdyuBxIijhmikvK/VbdstuQxy1ja0tfB2M4HEiANC9xPAr5CRrX7p5EAQMC9OzbOZ+MPZfMI3msQnfNXQZJTVvDiNF2ahH82Is1yvLxrHmBcHxEskZjUanVd+hoxjYxMBs+IEiqagl3EkawHvk3Y2thAwK44Qurlmp2DS2IqWUvAGScCcOHunqQfcItKrgFIQJR2YQ0bm0u2N5sTpMUDd0m4kCDYAhDYRdjZFETAnjmU/FOWreVfAHsjd/icZx8YIAubEATk1wlN4JwRfhzf525mAGXG2+G0cgc4hXUtLzbThEAcBM+IMaxyNI9B9CP+14L3rJGFnE0HAjDgheyLhC0dx4Aj30kgypNGMOFJqHjzFEbIUbCQJmBEHxGjSm5THSTsbSQKGxJEjSW/S+om0s5Ek4L446j0AgDtIb3bjWdLORpKA++IcKVCjAj0Jb1f44ZOg4mByX5x6z80af79p7GzWEHBfnExcxoQM+MIshw4RcF+ckOxPl0BcpO1s1RFwXxxb9NM4u6yxs1lDwH1xgrKvxletxs5mDQH3xRGatwckpO17Nhr2Mc3uiyMhi/RqAc+DJsHoje6LYwm1tEn7IIEeDG2fki3/EXBfHCGOaug+DM1vTmui2RxNwH1xrIFq+au/oh3hPr4CIl8m7GzSEHBfHDUpXcDnpD81VSpQOJSMY2M7Au6Lo1zYwVX4t7GdNwCcN20vIexsIgiYESen4izewtYR/tQiqPNgf9EtZBwbIwiYEafJhecN/MI5atFB9gSP0L1IFZ04rffNiePdfA7JfkbSlbAAjj2he6OaPCQdjWbfCZWht8Gy5uLEjsiTQMAAuFr3PAJfkXToahrXUDkNgnI8zkA5BHnjA6kyCcX8IhEB307svc0gRKiFYHACTMH2KVmhyj8GV2nfgOVrfUAWYj3sGjsfSpI/lzvyjDYCSbyrybYv2PZuOFioX2NNc6Ar5upifBUyVBMhjMpYrZI4/YTPFR+dzMS8ON6yfVjjPZpyDgfLroRDxWqp+8QEtVRllW81ivApOqTHAUHem5jCOHsxL47yLyW2L6KeLIqAmzB+D1T7VBtkNqj/e1Ab3IdOnovhKCWmDJtvc8IUqnwKyOrwruZ7G/QIPg0TKujBU81BcZkPFk0CW6glKJ2fsSSsBG/54rjyNJwoMVeOqkReeSlYcmmM+hRBvX0Mqv0PxEjXsehqXyEKsw8P0gsj4DL+S5Y5KMyLHcvcXOrEXTnhOlQXL8LbmBrecTox1Oy3j7HBXvK/p1OpRV2D4nG8p85GX/QM1HCZAE5jr60QvNtTatJj4sVRQCqLZ+BVtBG3bmjlQ27h6LbcCiFc0jhT/gieXue1Kxeq1xwzemMPMGs05q1Gv2fiJ576VUCGNQ9ytqbcHId4Ck9S67RRLYpnhdTqHcnqGYVwnG8pTC57CyWUna6PgQySJ46qjOrW/h18ByEtMlA3fZYS6tHnLFx4T3UQUjYkV5wwloBP/dsttebn4LDJ3Lc4j23ZbMjblhLdZad6OjXKTse5G+ct3wkN9WMw01L8BN3NvCW3o7i1ABqvj+oKwqhSp8aV08IPNyr947BBX44dgem4hz/OdSpghwLXDc2wPsIG/3inckrCwaknThjC9/gfp65lPIK3IBRJjMDu92BsJ9Qk+T7hJFHf6rcjNeX3IjbvZ1DcjVDfbwfcv44emYg6mHeZABNgAkyACTABJsAEmAATYAJMgAkwASbABJgAE2ACTIAJMAEmwASYQEcJ/AsEkdDxRqxiGQAAAABJRU5ErkJggg==

-------------------------------

Result: {"foundText":false}

**Comment by ChrisTomAlx** [comment]
Is this your image?

<img src="https://user-images.githubusercontent.com/34361280/84567657-b1084e80-ad97-11ea-916b-b8384cd52607.png" width="100">


This looks like handwritten text. Although this plugin could work with really neatly written text it is meant for machine generated text. The model has been trained with those. To test this you can click a pic of a page in a printed book or a business card and then get the text.

Closing this issue for now as it does not seem to need anymore clarification. Let me know if you need more help

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by dzungcao** [comment]
Hi Chris,

Yes, I am trying to detect single handwritten characters.

Thanks for your quick response.
