### ISSUE TITLE
Orientation issue on upload

### ISSUE THREAD

**Issue by tushar-agg** [NeutrinosPlatform/cordova-plugin-mobile-ocr#39]
on uploading image that is of 90 degrees orientation. the returned value is {'foundText':false}, no text is returned from api.

**Comment by ChrisTomAlx** [comment]
Hey @tushar-agg, Thanks for raising this issue. But unfortunately the plugin expects the image input to have text that is upright. You can do some post-processing with other plugins on the image before using it as input to this plugin. 

Making changes to the image is out of scope of this plugin.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by tushar-agg** [comment]
Hi Christy,

Just want to ask one thing
1. Is this plugin has any free tier limit or we can use it for any number
of images for ocr?

2. Is there any major issues in this plugin as we are planning to roll out
this plugin in production

Thanks
Tushar

**Comment by ChrisTomAlx** [comment]
1. No limit you are free to use it without any restrictions
2. I am not sure if there are issues, but UIWEBVIEW deprecation could be an issue for ios. You can instead also try https://github.com/NeutrinosPlatform/cordova-plugin-ml-text which was recently updated.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
