### ISSUE TITLE
Does not working in html code

### ISSUE THREAD

**Issue by merbin2012** [NeutrinosPlatform/cordova-plugin-mobile-ocr#4]
I am trying to scan the HTML programs, but it doesn't read the symbols properly
for example

&lt;ul&gt;
&lt;li&gt;one&lt;/li&gt;
&lt;li&gt;Two&lt;/li&gt;
&lt;/ul&gt;
&lt;style&gt;
ul{list-style-type:none;}
li{display:inline-block;}
&lt;/style&gt;

**Comment by ChrisTomAlx** [comment]
Hi @merbin2012 

Could you show me the image you captured and the detected response?

Also you could try the cordova-plugin-ml-text plugin. It might give a more accurate response. But it requires firebase.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by merbin2012** [comment]
Thank you very much for the quick response. Please see the below attached file

![1545821927900](https://user-images.githubusercontent.com/3687184/50445657-2c710880-0936-11e9-9d39-523e13272139.jpg)
![1545821917949](https://user-images.githubusercontent.com/3687184/50445658-2c710880-0936-11e9-8fef-2078e9345a95.jpg)
![1545821987801](https://user-images.githubusercontent.com/3687184/50445659-2d099f00-0936-11e9-8a34-d951a443e5f9.jpg)

**Comment by ChrisTomAlx** [comment]
Are you trying to take the pic from your screen? Could you try by printing the html onto a paper and then taking the pic or using a screen shot of the html code.. Taking pics from screen tend to produce erroneous results. 

Also could you show me your code, so I understand the options you have used to run the ocr. 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by merbin2012** [comment]
But google translator reading perfectly.

**Comment by merbin2012** [comment]
Hi! Can you fix this? Especially symbols are not working like <,>

**Comment by ChrisTomAlx** [comment]
There is not much that can be done about accuracy, if you can show me how you used the plugin I can see if there are any performance improvements you can implement.

You can also try the [ml-text plugin](https://github.com/NeutrinosPlatform/cordova-plugin-ml-text). In my tests it gave better accuracy. Usage is almost similar.

Sorry I couldn't be of more help.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by merbin2012** [comment]
Thank you very much. Is ml-text plugin uses google's algorithm? Because it required firebase, that's why I asking

**Comment by ChrisTomAlx** [comment]
Yes it does! Google just took the mobile vision library used in this plugin and integrated it into firebase. They then stopped support for the mobile vision library and only support it through firebase. Hence two plugins that perform similar functionalities were born.

Closing this issue for now. If you decide to use the ml-text plugin and run into problems then raise an issue there.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
