### ISSUE TITLE
IOS not recognize text, project created on Apple M1.

### ISSUE THREAD

**Issue by xataramana** [NeutrinosPlatform/cordova-plugin-mobile-ocr#40]
Project with mobile-ocr plugin created on Apple M1, xcode 12.3, cordova 10.0.0 cordova-ios 6.1

Plugin see data from image (from camera) but  recognize wrong text. For example for "Some text on image", plugin returns something like "cw Fd".

Perhaps problem because Pods. During instalation "pod update" return error. On the web I found other problems because Pods and Apple Silicone. 

P.S. the same project on Android devices  recognize text correctly. 

Doing pod update:
### Error
```
LoadError - dlsym(0x7fb238990e40, Init_ffi_c): symbol not found - /Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.0/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:133:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:133:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:131:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/sources_manager.rb:131:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command/update.rb:63:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ―――――――――――――

[!] Oh no, an error occurred.

**Comment by ChrisTomAlx** [comment]
You can try using https://github.com/NeutrinosPlatform/cordova-plugin-ml-text as well

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by xataramana** [comment]
Thank you, for response. Unfortunately, error while installing (I ran terminal with option "open with rosetta" and without rosetta)

Installing "cordova-plugin-ml-text" for ios
Running command: pod install --verbose
Failed to install 'cordova-plugin-ml-text': Error: pod: Command failed with exit code 1
    at ChildProcess.whenDone (../platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:136:25)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
pod: Command failed with exit code 1

**Comment by xataramana** [comment]
I did: 
**cordova plugin add https://bitbucket.org/bhivedevs/cordova-plugin-ml-text.git**

Now I have plugin files in project folder _node_modules_ and package.json has:
  "devDependencies": {
    "cordova-android": "^9.0.0",
    "cordova-browser": "^6.0.0",
    "cordova-ios": "^6.1.1",
    "cordova-plugin-ml-text": "bitbucket:bhivedevs/cordova-plugin-ml-text",
...

**cordova build**  finish without errors, but after launch and deviceready no object mltext available, app is not respond -> white screen. 

**cordova plugin ls** not show this plugin in project

How to enable plugin from node_modules in project?

P.S. The same situation with  cordova plugin add https://bitbucket.org/bhivedevs/cordova-plugin-mobile-ocr.git

**Comment by ChrisTomAlx** [comment]
Why don't you use `cordova plugin add cordova-plugin-ml-text` ? Github has the latest code for both the plugins and they are hosted on npm as well so you don't need bitbucket.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by xataramana** [comment]
On Apple M1 I have one error after another.

`cordova plugin add cordova-plugin-ml-text` at first time was error (see top), then I made some tricks like 
`arch -x86_64 sudo gem install cocoapods`
`arch -x86_64 sudo gem install ffi`
`arch -x86_64 pod install` 
and plugin was installed without error but running `cordova build ios` return

_error: Resource "/Users/raman/Library/Developer/Xcode/DerivedData/HelloWorld-ccdqwxyfdtpjaobwtgvgkeustdcs/Build/Products/Debug-iphonesimulator/**MLKitTextRecognition/GoogleMVTextDetectorResources.bundle**" not found. Run 'pod install' to update the copy resources script.
** BUILD FAILED **_

Doing `pod install` looks like everything is fine
_Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 11 total pods installed._

then `cordova build ios` and the same error, no file found so I copy manually this MLKitTextRecognition/GoogleMVTextDetectorResources.bundle
again run `cordova build ios` BUILD SUCCEEDED!

Test on simulator -> Great!, Try app on device -> Error in xcode: _Thread 1: signal SIGABRT_

Fight is not over...

**Comment by xataramana** [comment]
Finally I returned to mobile-ocr. On android - no problem. 
I see errors in terminal while building on cordova for ios, but app on iOS is working

I found that problem is in other sphere. Text on iOS is not recognized from picture taken from camera, but if I select the same picture from library -> text is recognized.

**Comment by xataramana** [comment]
Finally I returned to mobile-ocr:
`cordova build ios` every time return errors, but on device (or simulator) app is working.

Probably the global problem was because I have not used options `targetWidth` and `targetHeight` in camera plugin. 
I added this to camera plugin and now OCR plugin works fine in ios!
Closed.

P.S. OCR on android works fine without this camera options.

**Comment by ChrisTomAlx** [comment]
Oh that is great to know. Glad you were able to get it to work.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
