### ISSUE TITLE
Please be more verbose on iOS setup

### ISSUE THREAD

**Issue by jfoclpf** [NeutrinosPlatform/cordova-plugin-mobile-ocr#41]
I'm not that versed in iOS. Can you be more verbose on the iOS setup?

> For iOS please also follow the steps below.

> Once the iOS platform is added in command line, change directory to where podfile is found. Example location :- (myapp/platforms/ios).
Make sure you have cocoapods installed then in command line do pod update.
Now open myapp.xcworkspace which is usually found in the same directory as the podfile, then build and run.
Note :- if you use myapp.xcodeproj to build and run, it will not work and it will show a linker error.
Note :- if you manually create the podfile, please refer to issue #2

I did this from my app directory

```
cd platforms/ios
pod update
```

Till now, ok!

What do you mean exactly with "Now open myapp.xcworkspace which is usually found in the same directory as the podfile, then build and run"?

How do I build and run?

**Comment by ChrisTomAlx** [comment]
You can open the xcworkspace file in xcode and build run there or after pod install use build flags along with `cordova build` to build on the cli. Refer the official cordova website for more details about build flags.

Please feel free to raise a pr for the readme, if you think I have missed something. 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
**Here is an example build cli command with build flags :-**
```sh
cordova build ios --device --codeSignIdentity="iPhone Developer" --developmentTeam="<yourTeamId>" --buildFlag="-allowProvisioningUpdates" --buildFlag="-UseModernBuildSystem=0"
```
You might have to change some things based on your setup.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
