### ISSUE TITLE
Not working with cordova-plugin-background-geolocation

### ISSUE THREAD

**Issue by tepeonde** [NeutrinosPlatform/cordova-plugin-mobile-ocr#46]
I try to use this plugin with the cordova-plugin-background-geolocation or @mauron85/cordova-plugin-background-geolocation. I cannot get a project build or compiled even with just only these two plugins. The error messages is:

D:\Cordova\Multitrans3\platforms\android\gradlew: Command failed with exit code 1 Error output:
D:\Cordova\Multitrans3\platforms\android\app\src\main\java\com\marianhello\bgloc\data\BackgroundActivity.java:20: error: cannot access zzbfm
confidence = activity.getConfidence();
^
class file for com.google.android.gms.internal.zzbfm not found
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

My Environment is

    Plugin version: 3.0.3 / 3.1.2
    Platform: Android 8.x
    Cordova version: 11
    Cordova platform version (cordova platform ls): 8.1.0

Steps to Reproduce

    Create a new cordova project
    cordova plugin add [@mauron85/]cordova-plugin-background-geolocation
    cordova plugin add cordova-plugin-mobile-ocr
    cordova platform add android@8
    cordova build android

I tried also android@9 and android@10 without success. Each plugin for its own do work correctly, but not both together.

**Comment by ChrisTomAlx** [comment]
Hey @tepeonde 
You can instead try this [plugin](https://github.com/NeutrinosPlatform/cordova-plugin-ml-text). It does pretty much the same.

**Comment by tepeonde** [comment]
Thank you @ChrisTomAlx for the tip, but as you say "it does pretty much the same". Yes, it also throws the same error as for cordova-plugin-mobile-ocr :(

**Comment by ChrisTomAlx** [comment]
Seems like it could be an [issue ](https://stackoverflow.com/questions/50732704/cannot-access-zzbfm-class-file-zzbfm-not-found-firebase-android)with mixing versions. You could try changing the version to a matching one in the framework tag within plugin.xml, for both plugins and see if that works.

**Comment by tepeonde** [comment]
Hello @ChrisTomAlx, thank for that tip too. But i cannot get it build. Tried to set the versions in framework tag to the same version. I would appreciate when you help me solving this problem. I am willing to pay for for time and help.

**Comment by tepeonde** [comment]
We have solved this issue with some investigation on google. The solution for us was:

•	Use cordova-android 10
•	Added background plugin with --variable GOOGLE_PLAY_SERVICES_VERSION=17+
•	Added the following line to app\build.grade in dependencies section:
implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'

Hope this will also help others.
