### ISSUE TITLE
Need to convert image to text

### ISSUE THREAD

**Issue by kalaiprakash93** [NeutrinosPlatform/cordova-plugin-mobile-ocr#5]
Nothing happend when using in this plugin in android 8.0.0.can u tel me wat was the issue?

navigator.camera.getPicture(onSuccess, onFail, { quality: 100, correctOrientation: true,destinationType: Camera.DestinationType.DATA_URL  });
 
function onSuccess(imageData) {
		alert(imageData);
      textocr.recText(0, 3, imageData, onSuccess, onFail);
      // for sourceType Use 0,1,2,3 or 4
      // for returnType Use 0,1,2 or 3 // 3 returns duplicates[see table]
      function onSuccess(recognizedText) {
            var element = document.getElementById('take_photo');
            element.innerHTML=recognizedText;
            //Use above two lines to show recognizedText in html
            console.log(recognizedText)
            alert(recognizedText);
      }
      function onFail(message) {
            alert('Failed because: ' + message);
      }
}
function onFail(message) {
      alert('Failed because: ' + message);
}

**Comment by ChrisTomAlx** [comment]
Try using this instead and let me know if you still have no response.

```js 
navigator.camera.getPicture(onSuccess, onFail, { quality: 100, correctOrientation: true });

function onSuccess(imageData) {
      textocr.recText(0, 3, imageData, onSuccess, onFail);
      // for sourceType Use 0,1,2,3 or 4
      // for returnType Use 0,1,2 or 3 // 3 returns duplicates[see table]
      function onSuccess(recognizedText) {
            //var element = document.getElementById('pp');
            //element.innerHTML=recognizedText;
            //Use above two lines to show recognizedText in html
            console.log(recognizedText);
            alert(recognizedText);
      }
      function onFail(message) {
            alert('Failed because: ' + message);
      }
}
function onFail(message) {
      alert('Failed because: ' + message);
}

```

If you absolutely must use `destinationType: Camera.DestinationType.DATA_URL` then try using the following snippet :- 

```js 
navigator.camera.getPicture(onSuccess, onFail, { quality: 100, correctOrientation: true,destinationType: Camera.DestinationType.DATA_URL});

function onSuccess(imageData) {
      textocr.recText(4, 3, imageData, onSuccess, onFail);
      // for sourceType Use 0,1,2,3 or 4
      // for returnType Use 0,1,2 or 3 // 3 returns duplicates[see table]
      function onSuccess(recognizedText) {
            //var element = document.getElementById('pp');
            //element.innerHTML=recognizedText;
            //Use above two lines to show recognizedText in html
            console.log(recognizedText);
            alert(recognizedText);
      }
      function onFail(message) {
            alert('Failed because: ' + message);
      }
}
function onFail(message) {
      alert('Failed because: ' + message);
}

```

In the above snippet I have added the `destinationType: Camera.DestinationType.DATA_URL` to the options array and I have changed sourceType to 4 so that the ocr plugin knows that the incoming imagedata is of base64 type.

Hope this helps!!

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by kalaiprakash93** [comment]
first i have tried ur first method only..its opening camara and capturing pic.it is not triggers error or success in textocr function

**Comment by ChrisTomAlx** [comment]
@kalaiprakash93 

I tested this with android 8 and did not run into any issues.

Could you debug using android studio and sent the stack trace ? Or sent me your project so I can check it on my end (Or create a blank project with just this plugin, make sure it isn't working and then sent it over)

Cheers & Happy Holidays!
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by kalaiprakash93** [comment]
config.xml:
`<?xml version='1.0' encoding='utf-8'?>
<widget id="com.phonegap.helloworld" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>Device Features</name>
    <description>
        A basic Framework7 template for PhoneGap.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
	<preference name="phonegap-version" value="cli-7.1.0" />  
        <preference name="android-minSdkVersion" value="14" />
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <preference name="BackupWebStorage" value="none" />
    </platform>
    <preference name="DisallowOverscroll" value="true" />
    <plugin name="cordova-plugin-whitelist" spec="~1.2.0" />
    <plugin name="cordova-plugin-console" spec="~1.0.1" />
    <plugin name="cordova-plugin-statusbar" spec="~1.0.1" />
    <plugin name="cordova-plugin-mobile-ocr" spec="*" />
    <plugin name="cordova-plugin-camera" spec="*" />
	<plugin name="cordova-plugin-android-permissions" source="npm" />
</widget>
`
index.html
`<!DOCTYPE html>
<html>
<head>
    
    <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">

    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">

    
    <title>My App</title>

    

    <link rel="stylesheet" href="lib/framework7/css/framework7.ios.min.css">
    <link rel="stylesheet" href="lib/framework7/css/framework7.ios.colors.min.css">

    <link rel="stylesheet" href="css/styles.css">
</head>

<body>
    <div class="views">
        
        <div class="view view-main">
            
            <div class="navbar">
                <div class="navbar-inner">
                    
                    <div class="center sliding">Awesome App</div>
                    <div class="right">
       
                    </div>
                </div>
            </div>
            
            <div class="pages navbar-through toolbar-through">
                
                <div data-page="index" class="page">
                    
                    <div class="page-content">
                        <div class="content-block">
                           
                        </div>
                    </div>
                </div>
            </div>
           
        </div>
    </div>

    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="lib/framework7/js/framework7.min.js"></script>
    <script type="text/javascript" src="js/my-app.js"></script>
</body>

</html>`
my-app.js
`// Initialize app
var myApp = new Framework7();


// If we need to use custom DOM library, let's save it to $$ variable:
var $$ = Dom7;

// Add view
var mainView = myApp.addView('.view-main', {
    // Because we want to use dynamic navbar, we need to enable it for this view:
    dynamicNavbar: true
});

// Handle Cordova Device Ready Event
$$(document).on('deviceready', function() {
    console.log("Device is ready!");
	var permissions = cordova.plugins.permissions;


		permissions.hasPermission( permissions.CAMERA, success, error);

		function error(e) {
		  console.log('Permissions not enabled'+JSON.stringify(e));
		}
		function success( status ) {
		  if( !status.hasPermission ) {
		  
			permissions.requestPermissions(
			  permissions.CAMERA,
			  function(status) {
				if( !status.hasPermission ) error(e);
			  },
			  error);
		  }
		}
	navigator.camera.getPicture(onSuccess, onFail, { quality: 100, correctOrientation: true,destinationType: Camera.DestinationType.DATA_URL});

	function onSuccess(imageData) {
		  textocr.recText(4, 3, imageData, onSuccess, onFail);
		  // for sourceType Use 0,1,2,3 or 4
		  // for returnType Use 0,1,2 or 3 // 3 returns duplicates[see table]
		  function onSuccess(recognizedText) {
				//var element = document.getElementById('pp');
				//element.innerHTML=recognizedText;
				//Use above two lines to show recognizedText in html
				console.log(recognizedText);
				alert(recognizedText);
		  }
		  function onFail(message) {
				alert('Failed because: ' + message);
		  }
	}
	function onFail(message) {
		  alert('Failed because: ' + message);
	}
});
`

**Comment by ChrisTomAlx** [comment]
Hey @kalaiprakash93 

Could you please send it as a project rather than as code?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by kalaiprakash93** [comment]
[Device Features.zip](https://github.com/NeutrinosPlatform/cordova-plugin-mobile-ocr/files/2717874/Device.Features.zip)

**Comment by ChrisTomAlx** [comment]
@kalaiprakash93 

I removed platform browser and permission plugin.
Then I added the permission plugin back and added platform android and built and run.
It worked as expected.

This plugin does not support browsers so if you are trying to test on browser it won't work.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Closing since there has been no response. Please reopen if you need to,

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by kalaiprakash93** [comment]
I removed platform browser and permission plugin.
Then I added the permission plugin back and added platform android and built and run.
It worked as expected.

This plugin does not support browsers so if you are trying to test on browser it won't work.

i couldn't able to understand this.

**Comment by ChrisTomAlx** [comment]
@kalaiprakash93 

Are you testing this plugin in your browser?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by kalaiprakash93** [comment]
no..in mobile only android 8.0.0 honor &A pro

**Comment by ChrisTomAlx** [comment]
@kalaiprakash93 

May I ask which version of cordova and cordova-android you are using?


Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by kalaiprakash93** [comment]
Am using phonegap online build cli version is 7.1.0 and cordova-android version -6.3.0

**Comment by ChrisTomAlx** [comment]
@kalaiprakash93 

Could you run cordova platforms on the command line and send a screen shot of what you see.

Also do you have android studio installed?

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by kalaiprakash93** [comment]
no..i will try it at  night and let u know.I am in office now..Here i cannot use studio and cordova.
Thank you for your response.

**Comment by ChrisTomAlx** [comment]
@kalaiprakash93 

Sure no problem, my pleasure.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by maheshlakshmipathi** [comment]
Hello,

This plugin isn't reading the text, after the camera captures the image there is no output. what has to be done, Iam using phonegap to test this

**Comment by ChrisTomAlx** [comment]
Hey @maheshlakshmipathi 

Could you send me your project folder as a zip or a new project with just this plugin (and its requirements) and the code you used. So that I can test it and say what might be wrong. You have given me no information to help you with your problem so hence the request for your project.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by maheshlakshmipathi** [comment]
Hello chris,

[device_features.zip](https://github.com/NeutrinosPlatform/cordova-plugin-mobile-ocr/files/2887846/device_features.zip)


Thanks for the reply, iam attaching the file that i have been using, iam using phone gap to build the app. as already said the camera is capturing the image but the OCR feature is not been applied.

Thanks in advance for your help

**Comment by ChrisTomAlx** [comment]
Will look into it and get back to you as soon as I can :)

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
@maheshlakshmipathi  It seems to be working fine for me. All I had to do was change the min sdk version in the config.xml to 16, this was causing the build to fail. I built and ran the app. The camera opened and text was detected.

Could you try uninstalling the app from the test phone, then rebuilding and installing? Do this entire process with an internet connection on the phone and let me know if it helps? If that doesn't we will find our way from there.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by maheshlakshmipathi** [comment]
Yep thanks, 
it scanned the image now but getting an error called "exception". what is the problem?

**Comment by ChrisTomAlx** [comment]
My friend @maheshlakshmipathi, I will need more information than just that to help you. Please send screenshots, stack traces, etc..

Please refer to [this](https://cordova.apache.org/docs/en/latest/guide/next/#debugging-cordova-apps) for help with debugging.
Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
Hey guys, closing this issue since there hasn't been any updates for a while.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by basitraza339** [comment]
Hello,

This plugin isn't reading the text, after the camera captures the image and show it. After click, recognize button getting exception error, I'm using ionic 4.

tab2.ts
`import { Component } from '@angular/core';
import { Camera, CameraOptions, PictureSourceType } from '@ionic-native/camera/ngx';
import { NavController, ActionSheetController, Platform, LoadingController } from '@ionic/angular';
import { OCR, OCRSourceType } from '@ionic-native/ocr/ngx';

@Component({
  selector: 'app-tab2',
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss']
})
export class Tab2Page {

  selectedImage: string;
  imageText: string;

  constructor(public navCtrl: NavController,
    private camera: Camera,
    private actionSheetCtrl: ActionSheetController,
    private loading: LoadingController,
    public platform: Platform,
    private ocr: OCR) 
    {

    }
  
    async selectSource() {
      const actionSheet = await this.actionSheetCtrl.create({
          header: 'Select Source',
          buttons: [
              {
                  text: 'Capture Image',
                  role: 'camera',
                  icon: 'camera',
                  handler: () => {
                      return this.getPicture(this.camera.PictureSourceType.CAMERA);
                  }
              },
              {
                  text: 'Use Libary',
                  role: 'libary',
                  icon: 'folder-open',
                  handler: () => {
                      return this.getPicture(this.camera.PictureSourceType.PHOTOLIBRARY);
                  }
              }
          ]
      });
      await actionSheet.present();
  }

  getPicture(sourceType: PictureSourceType) {
      if (this.platform.is('cordova')) {
          this.camera.getPicture({
              quality: 100,
              destinationType: this.camera.DestinationType.DATA_URL,
              sourceType: sourceType,
              allowEdit: true,
              saveToPhotoAlbum: false,
              correctOrientation: true
          }).then((imageData) => {
              this.selectedImage = `data:image/jpeg;base64,${imageData}`;
          });
      } else {
          alert('cordova not available');
      }

  }

  

  recognizeImage() {
	  this.ocr.recText(OCRSourceType.NORMFILEURL, "this.selectedImage")
  	.then((res) => console.log(JSON.stringify(res)))
  	.catch((error: any) => console.error(error));
  }
}`

config.xml
`<?xml version='1.0' encoding='utf-8'?>
<widget id="io.ionic1.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyApp</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework.com" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content src="index.html" />
    <access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="ScrollEnabled" value="false" />
    <preference name="android-minSdkVersion" value="19" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <platform name="android">
        <edit-config file="app/src/main/AndroidManifest.xml" mode="merge" target="/manifest/application" xmlns:android="http://schemas.android.com/apk/res/android">
            <application android:networkSecurityConfig="@xml/network_security_config" />
        </edit-config>
        <resource-file src="resources/android/xml/network_security_config.xml" target="app/src/main/res/xml/network_security_config.xml" />
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <icon height="20" src="resources/ios/icon/icon-20.png" width="20" />
        <icon height="40" src="resources/ios/icon/icon-20@2x.png" width="40" />
        <icon height="60" src="resources/ios/icon/icon-20@3x.png" width="60" />
        <icon height="48" src="resources/ios/icon/icon-24@2x.png" width="48" />
        <icon height="55" src="resources/ios/icon/icon-27.5@2x.png" width="55" />
        <icon height="29" src="resources/ios/icon/icon-29.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-29@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-29@3x.png" width="87" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="88" src="resources/ios/icon/icon-44@2x.png" width="88" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="172" src="resources/ios/icon/icon-86@2x.png" width="172" />
        <icon height="196" src="resources/ios/icon/icon-98@2x.png" width="196" />
        <icon height="1024" src="resources/ios/icon/icon-1024.png" width="1024" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="1125" src="resources/ios/splash/Default-Landscape-2436h.png" width="2436" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="2436" src="resources/ios/splash/Default-2436h.png" width="1125" />
        <splash height="2732" src="resources/ios/splash/Default@2x~universal~anyany.png" width="2732" />
    </platform>
    <plugin name="cordova-plugin-whitelist" spec="1.3.3" />
    <plugin name="cordova-plugin-statusbar" spec="2.4.2" />
    <plugin name="cordova-plugin-device" spec="2.0.2" />
    <plugin name="cordova-plugin-splashscreen" spec="5.0.2" />
    <plugin name="cordova-plugin-ionic-webview" spec="^4.0.0" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-camera" spec="^4.1.0" />
    <plugin name="cordova-plugin-mobile-ocr" spec="^3.1.1" />
    <engine name="android" spec="^7.0.0" />
</widget>
`
