### ISSUE TITLE
Success callback returning exception String

### ISSUE THREAD

**Issue by renzified** [NeutrinosPlatform/cordova-plugin-mobile-ocr#7]
`navigator.camera.getPicture(function(imagedata){
            textocr.recText(0, 3, imagedata, function(text){
                alert(text);
            }, function(e){
                alert(e);
            });
        }, function(e){
            alert(e);
        }, { quality: 100, correctOrientation: true });`

the success callback in the ocr alerts string "Exception"

**Comment by ChrisTomAlx** [comment]
Hey @thekingrenz23 

What version of the plugin are you using? 

If you are using 2.x.x then remove the returntype (here 3). So your code would change to :

`navigator.camera.getPicture(function(imagedata){ textocr.recText(0, imagedata, function(text){ alert(text); }, function(e){ alert(e); }); }, function(e){ alert(e); }, { quality: 100, correctOrientation: true });` 

> Notice I removed the 3

Let me know if it helps or if it didn't. We will see what to do from there.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)
