### ISSUE TITLE
Getting 'Could not set up the detector' error

### ISSUE THREAD

**Issue by svankamamidi** [NeutrinosPlatform/cordova-plugin-mobile-ocr#9]
Integrated as provided in the ReadMe instructions but after passing the image I am getting error 'Could not set up the detector'

**Comment by ChrisTomAlx** [comment]
Hey @svankamamidi 
Please share your project / code & project details mainly cordova versions, plugin version and test device details

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChrisTomAlx** [comment]
@svankamamidi 

Another thing, make sure you have your internet on when you are installing the app to device.
Because the detector files are downloaded when the app is being installed. Let me know if this helps.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by svankamamidi** [comment]
> @svankamamidi
> 
> Another thing, make sure you have your internet on when you are installing the app to device.
> Because the detector files are downloaded when the app is being installed. Let me know if this helps.
> 
> Cheers,
> [Chris](https://github.com/ChrisTomAlx)
> [Neutrinos](http://www.neutrinos.co/)

Yes I had corporate working WIFI connection.
Cordova version 8.1.2 (cordova-lib@8.1.1)

I am getting same error on device and in emulator as well

**Comment by svankamamidi** [comment]
Emulator: Nexus_5X_API_25

my code is very simple as given in the readme.

**Comment by ChrisTomAlx** [comment]
What about plugin version ? 
I am not sure you can test this on a simulator. Haven't tried it though. Could you uninstall the existing app, make sure the internet is working then reinstall the app ? 
It is working fine on my end. Sorry but I don't think I can help you much if you don't give me some way to recreate the issue.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by svankamamidi** [comment]
Plugin version is the latest. I will retry by uninstalling and will report.

**Comment by svankamamidi** [comment]
Same problem even after uninstalling and installing with WIFI internet, please ask me details what else you need to reproduce the bug. 
I have around 8 GB free space on device. My device is Moto G4 plus with Android 7.0

**Comment by ChrisTomAlx** [comment]
Could you send me your project folder or recreate the issue in a new project then send it over ? I will check it on my side

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by mantrajay** [comment]
I have the same issue like yours. have you solved this issue already? thanks

**Comment by ChrisTomAlx** [comment]
Hey @mantrajay 

Have you already tried the suggestions I have mentioned here? 
If not then please try them first. If you have then please create a new issue with explanations of what you have tried, what outputs you got. Also share your environment details (eg device you tested on, cordova version, cordova-android version and so on). If possible also share a simple project with this plugin, but make sure you are getting the same error in this project before sharing it with me.

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by mantrajay** [comment]
I am actually developing a mobile app that capture image and convert it in
ocr but suddenly there was an error like "Could not set the detector" i am
using Nokia 1 Android.. but wen i install it in other mobile like Zenephone
and Samsung it work.. but the requirements of this application is for Nokia
1 Android user only. please help thanks

**Comment by ChrisTomAlx** [comment]
Hey @mantrajay 
Please do not hijack closed issues. You need to open a new issue if you need help.
As for the nokia user. Ask the user to uninstall the app then reinstall with internet connectivity. 

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by mantrajay** [comment]
yes thanks.. but i have done that already.. still same error. but when i
try to other latest phone it is working fine. only on nokia 1 android does
not work and it prompt could not set up detector.

**Comment by ChrisTomAlx** [comment]
@mantrajay 
I checked out the nokia 1 configuration.. It has very little storage. Could you check how much free space is available on the device ? 

Try freeing up some more space then reinstall with the wifi on. Let me know if that works

Cheers,
[Chris](https://github.com/ChrisTomAlx)
[Neutrinos](http://www.neutrinos.co/)

**Comment by ChaminThilakarathne** [comment]
Can we set up detector separately?
